MTUIDEMO ;
 D ^MTUI("MTUIDEMO","MTUI Library Demo")
 D INIT^MTUI
 D ADDACCEL^%TERMIO("KEY_F9","D QUITDEMO^MTUIDEMO","F9","QUIT")
PRIMARY ;
 N MA
 S MA("TITLE")="MAIN MENU"
 S MA("ITEMS","CALENDAR CONTROL")="D CALCTL^MTUIDEMO"
 S MA("ITEMS","FORM CONTROL")="D FORMCTL^MTUIDEMO"
 S MA("ITEMS","QUIT "_MTUIAPP)="D QUITDEMO^MTUIDEMO"
 D GO^MTUIMENU(.MA)
 G PRIMARY
 Q
 ;;
CALCTL ;
 D GO^MTUIDATE("1/1/1970","Date Picker Demo")
 D MSGBOX^MTUI("Selected date: "_EXTVAL,"","Date Picker Demo")
 Q
 ;;
FORMCTL ;
 Q
 ;;
QUITDEMO ;
 S RESP=$$CONFIRM^MTUI("REALLY QUIT?")
 I RESP="Y" D
 . D RESET^MTUIUTIL
 . HALT
 Q