MTUIFILE
 Q
 ;;
VIEW(FILE,CAPTION)
 N EV,KEY,CONTENTS,STARTLINE,SCRLINE,LINES 
 S LINES=0,SCRLINE=3,STARTLINE=1
 S LINES=$$LOAD(FILE,.CONTENTS)
REDISPLAY
 D INIT^MTUI
 D CAPTION^MTUI(CAPTION)
 D SETCOLOR^MTUIUTIL("CYAN","BLACK")
 S SCRLINE=3
 U $P:(NOWRAP)
 F I=STARTLINE:1:STARTLINE+(%IOCAP("ROWS")-5)  D
 . D LOCATE^MTUIUTIL(SCRLINE,1)
 . W $G(CONTENTS(I))
 . S SCRLINE=SCRLINE+1
IO
 D LOCATE^MTUIUTIL(%IOCAP("ROWS"),1),SETCOLOR^MTUIUTIL("MAGENTA","BLACK")
 D SETATTR^MTUIUTIL("BRIGHT") W "F3:MAIL     F6:EXIT"
 D HOME^MTUIUTIL
 S QUITFLG=0
 S KEY=$$GETCH^%TERMIO(.EV)
 I KEY="KEY_UP" D
 . I STARTLINE>0 S STARTLINE=STARTLINE-1 G REDISPLAY
 I KEY="KEY_DOWN" D 
 . I STARTLINE<(LINES-19) S STARTLINE=STARTLINE+1 G REDISPLAY
 I KEY="KEY_F6" S QUITFLG=1
 I KEY="KEY_F3" D
 . D MAIL(FILE,CAPTION)
 G:QUITFLG=0 REDISPLAY
 D RESET^MTUIUTIL
 Q
 ;;
MAIL(FILE,CAPTION)
 N FA
 S FA("TITLE")="MAIL "_CAPTION
 S FA("ITEMS",1,"NAME")="TO"
 S FA("ITEMS",1,"LABEL")="TO: "
 S FA("ITEMS",1,"LABEL","TOP")=8
 S FA("ITEMS",1,"LABEL","LEFT")=40-$L(FA("ITEMS",1,"LABEL"))
 S FA("ITEMS",1,"FIELD","TOP")=8
 S FA("ITEMS",1,"FIELD","LEFT")=40
 S FA("ITEMS",1,"FIELD","MAXLENGTH")=35
 S FA("ITEMS",1,"FIELD","REQUIRED")=1
 S FA("ITEMS",1,"FIELD","PRESERVECASE")=1
 D GO^MTUIFORM(.FA)
 N TO S TO=$$GETEXTVAL^MTUIFORM(.FA,"TO")
 D MAILTO^MTUINET(TO,$TR(CAPTION," ","_"),"FILEBODY.TXT",FILE)
 Q
 ;;
LOAD(FILE,CONTENTS)
 N LINES,CURLINE S (LINES,CURLINE)=0
 O FILE:READONLY
 U FILE
 F  S CURLINE=CURLINE+1 R CONTENTS(CURLINE) Q:$ZEOF 
 S LINES=CURLINE
 U $P
 C FILE
 Q LINES
 
  
 